version: '3.7'

services:
  db:
    image: postgres
    container_name: postgres
    user: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

volumes:
  postgres_data:
